# Generated by Django 5.0.7 on 2024-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
